name: cicd catalog service
on:
  push:
    paths:
      - "catalog-service/**"
      - ".github/workflows/push-catalog.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./catalog-service
          file: ./catalog-service/Dockerfile
          push: true
          tags: bemodesty306/spring-catalog:${{ github.sha }}

      - name: Git config
        run: |
          git config --global user.email "bemodsty306@naver.com"
          git config --global user.name "junho100"

      - name: Check out k8s repo
        uses: actions/checkout@master
        with:
          repository: junho100/toy-msa-kube-native--resources
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: git push image tag to k8 repo
        env:
          GITHUB_REPO: ${{ github.repository.name }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          sed -i "s|image:.*|image: bemodesty306/spring-catalog:$GITHUB_SHA|g" catalog-service/deployment.yaml
          git add .
          git commit -m "Deploy: deploy image tag $GITHUB_SHA to k8s repo"
          git push -f --set-upstream origin master
